#!/bin/sh

echo "Docker build hook: " docker build --build-arg BUILDROOT_CONFIG="$BUILDROOT_CONFIG" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .

docker build --build-arg BUILDROOT_CONFIG="$BUILDROOT_CONFIG" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .