#!/bin/sh
#
# S12board_devices_init
#
# Create symlinks for gpio devices on SAMA5 based controllers
# (SCC-Air-Mk II, SCC 5 Port Router, ITC-3)
#
# Copyright (C) 2020 by      SWARCO Traffic Systems GmbH
#                            Guido Classen
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version
# 2 or later as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Modification History:
#   2020-11-09 gc: initial version
#


case "$1" in
  start | restart | reload)
        # break
        ;;
  stop)
        exit 0
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

echo initializing peripheral devices and GPIOs

if [ -f /sys/firmware/devicetree/base/model ]; then

export PLATFORM="`cat /sys/firmware/devicetree/base/model`"
. /etc/swarco/board/gpio.sh
. /etc/swarco/board/led.sh
. /etc/swarco/board/hardware-interface-naming.sh
fi

# Local Variables:
# mode: shell-script
# backup-inhibited: t
# End:
